public/css/login.css
public/css/styles.css
views/index.html
views/login.html

fixed padding on navbar
fixed responsive navbar
fixed logo position
fixed superposition with slider

fix: fixed responsive navbar

---

public/css/styles.css
views/productCart.html

• agregue la media query 1440px

feat: cart page html and css added

---

public/css/styles.css
views/catalogue.html

Se cambia tamaño del contenedor
Se agrega color de outline a al input num
se agrega vista desplegable
A corregir (transisión)

Tr 62 fix filtro

---

public/css/styles.css

Cambio de color del footer y margen del catálogo

fix: resolve tr 65

---

public/css/styles.css

⢀⡴⠑⡄⠀⠀⠀⠀⠀⠀⠀⣀⣀⣤⣤⣤⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ 
⠸⡇⠀⠿⡀⠀⠀⠀⣀⡴⢿⣿⣿⣿⣿⣿⣿⣿⣷⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀ 
⠀⠀⠀⠀⠑⢄⣠⠾⠁⣀⣄⡈⠙⣿⣿⣿⣿⣿⣿⣿⣿⣆⠀⠀⠀⠀⠀⠀⠀⠀ 
⠀⠀⠀⠀⢀⡀⠁⠀⠀⠈⠙⠛⠂⠈⣿⣿⣿⣿⣿⠿⡿⢿⣆⠀⠀⠀⠀⠀⠀⠀ 
⠀⠀⠀⢀⡾⣁⣀⠀⠴⠂⠙⣗⡀⠀⢻⣿⣿⠭⢤⣴⣦⣤⣹⠀⠀⠀⢀⢴⣶⣆ 
⠀⠀⢀⣾⣿⣿⣿⣷⣮⣽⣾⣿⣥⣴⣿⣿⡿⢂⠔⢚⡿⢿⣿⣦⣴⣾⠁⠸⣼⡿ 
⠀⢀⡞⠁⠙⠻⠿⠟⠉⠀⠛⢹⣿⣿⣿⣿⣿⣌⢤⣼⣿⣾⣿⡟⠉⠀⠀⠀⠀⠀ 
⠀⣾⣷⣶⠇⠀⠀⣤⣄⣀⡀⠈⠻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀ 
⠀⠉⠈⠉⠀⠀⢦⡈⢻⣿⣿⣿⣶⣶⣶⣶⣤⣽⡹⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀ 
⠀⠀⠀⠀⠀⠀⠀⠉⠲⣽⡻⢿⣿⣿⣿⣿⣿⣿⣷⣜⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀ 
⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣷⣶⣮⣭⣽⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀ 
⠀⠀⠀⠀⠀⠀⣀⣀⣈⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠇⠀⠀⠀⠀⠀⠀⠀ 
⠀⠀⠀⠀⠀⠀⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠃⠀⠀⠀⠀⠀⠀⠀⠀ 
⠀⠀⠀⠀⠀⠀⠀⠹⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠟⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀ 
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠛⠻⠿⠿⠿⠿⠛⠉

refactor: cart margin fixed

---

src/views/partials/navAdmin.ejs
src/views/partials/sidebar.ejs

⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⣶⣴
⠀⠀⠀⠀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣠⣤⠖⠛⠉⣉⡙⠛⠒⠢⢤⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢷⣄⠀⠀⣠⣿⣿⡿
⠀⠀⣠⣾⣿⣧⠀⠀⠀⠀⠀⠀⢀⣴⡿⠥⠤⠶⠚⠛⢿⣍⡉⠀⠀⠀⠈⠑⢄⠀⠀⠀⠀⠀⠀⠀⢀⡀⠈⡿⢄⣴⡏⢉⡿⠁
⠀⠀⠻⢿⣿⣿⣇⠀⠀⠀⠀⣰⣿⣿⣷⣶⣦⣤⣤⣤⣤⣯⣽⣶⣦⣤⣤⣴⣶⣷⡄⠀⠀⠀⠀⢠⣿⣿⣶⣧⢀⠏⢡⠞⠀⠀
⠀⠀⠀⠀⠈⠙⠻⣷⣄⣀⣴⣿⣿⣷⣶⣿⣿⣿⣿⣿⣿⣇⣽⣿⣯⣿⣿⣿⣿⣭⡝⣆⠀⠀⣠⣾⣿⠿⠛⢻⣾⡔⠁⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠈⣿⣻⣿⣿⣿⣿⣻⣿⣿⣿⣿⣧⡴⠿⠿⢿⣿⣿⣿⣿⣿⢿⣿⣾⠳⣶⡟⠉⠀⠀⠀⠘⣿⣧⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⡿⠋⠀⠈⠙⠛⠛⢻⡟⢉⣩⠿⠶⠶⡦⠀⠉⠙⠻⣿⠿⠯⠀⠈⠀⢻⠀⠀⠀⠀⠀⠀⠸⣿⣆⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⣰⠃⠀⠀⠀⠀⢀⣴⣿⣷⣾⣅⣀⠀⠀⢻⣯⡀⢀⣀⣹⣦⣄⠀⠀⠀⠘⠇⠀⠀⠀⠀⠀⠀⠹⣟⣆⠀⠀
⠀⠀⠀⠀⠀⠀⢀⡟⠀⠀⢀⣤⣶⠿⠋⠉⠙⠛⠿⣿⣿⣿⣿⣿⡿⠟⠛⠻⣿⣿⣿⣦⣄⠀⠸⡀⠀⢀⡠⠶⠒⢉⣹⠿⠀⠀
⠀⠀⠀⠀⠀⠀⢸⣇⠀⠀⡿⢋⣀⠀⠀⠀⠀⠀⢀⡀⠒⠋⠈⠻⡇⠀⠀⠀⠈⠙⣿⣿⣿⣷⡄⢹⢋⣁⡤⠔⠚⠉⠀⠀⠀⠀
⠀⠀⠀⠀⣠⣾⣿⡇⠀⠀⠀⠘⢿⣿⣿⣿⣿⡷⢾⣷⣤⣤⣤⣤⣵⣶⣶⣶⣶⣶⣿⡇⢹⠟⠀⢘⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⣠⣞⣯⠞⢻⡇⠀⠀⠀⠀⠈⠛⢿⣿⣿⣦⣾⣅⣰⣿⣈⣁⣽⣥⣼⣽⣿⡿⠃⠀⠘⠀⠀⡈⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⢀⡏⡽⠁⠀⠈⢿⣤⠀⠀⠀⠀⠀⠀⠩⣽⣿⡽⠯⠭⠭⠿⠟⠿⡿⠟⠋⠁⠀⠀⠀⠀⠀⢰⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⢸⢁⠇⠀⠀⠀⠀⢻⣆⠀⠀⠀⠀⠀⠀⠀⠉⠉⠛⠛⠛⠛⠛⠛⠿⣇⠀⠀⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⡾⢸⠀⠀⠀⠀⠀⠀⢻⣷⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣙⣓⡄⠀⠀⠀⠀⢠⠏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⢠⣧⡇⠀⠀⠀⠀⠀⠀⠀⣿⡟⣷⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢰⣘⠉⠉⠀⠀⠀⢀⡴⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⣼⡇⣷⠀⠀⠀⠀⠀⠀⠀⡟⠀⡞⠈⠓⠶⣤⣀⡀⠀⠀⠀⠀⠀⠈⢻⣧⣀⣠⠔⠊⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ …

feat: admin icons

---

public/css/styles.css
src/views/products/catalogue.ejs

ajustes css footer
ajustes css filosofia
cambio input type range en filtro

perf: changes css

---

src/controller/productController.js
src/routes/product.routes.js

Controlador que filtra por id el producto y lo envía a la vista

feat:product detail controller

---

src/views/adminArea.ejs

Vista dinámica que carga todos los productos

feat:dynamic view html

---

public/css/styles.css
src/controller/productController.js
src/views/products/catalogue.ejs

Método catálogo que muestra la lista de productos.
Edité en la vista de catálogo el bloque producto. 
Ajuste de css del bloque de producto en función a la vista.

feat: method and css

---

src/controller/usersController.js
src/middleware/multerMid.js
src/routes/users.routes.js

se agrego el nombre de img de perfil a atributos de usuario
se movió multer a nuevo directorio 'middleware' para mantener limpio users.routes.js, donde es requerido para implementación

refactor: multer on users routes

---

public/css/styles.css

Ajustes en CSS de la sección novedades

changes on news section styles.css

---

src/views/products/productDetail.ejs

Funcion al boton 'agregar a carrito' en la vista de detalle producto

feat: add function to button on product detail

---

src/views/products/productCart.ejs

Se resuelve los links de las imagenes en el carrito

fix: img links on product cart

---

package-lock.json
package.json
src/app.js
src/controller/usersController.js
src/routes/users.routes.js

Validación de usuario existente
• Email correcto
• Password correcto

feat:login validation

---

src/controller/usersController.js
src/middleware/adminMiddleware.js
src/middleware/authMiddleware.js
src/middleware/guestMiddleware.js
src/middleware/multerMidProducts.js
src/routes/product.routes.js
src/routes/users.routes.js

• Restricción en las rutas (usuario no registrado, usuario logeado, usuario administrador)
• Limites en las imágenes de producto
• Middlewares que comprueban tipo de usuario y si inicio sesión o no

feat:user routes restriction

---

public/css/login.css
src/controller/usersController.js
src/routes/users.routes.js
src/views/users/registro.ejs

se separa la vista login en dos vistas distintas , registro y login

feat: separate view login and register

---

public/css/styles.css
src/controller/productController.js
src/middleware/adminMiddleware.js
src/middleware/authMiddleware.js
src/middleware/guestMiddleware.js
src/routes/product.routes.js
src/views/products/catalogue.ejs
src/views/products/productCart.ejs

**• Métodos de `productController` actualizados**

feat:cart method using cookies

---

public/css/admin.css
public/css/styles.css
src/controller/productController.js
src/controller/usersController.js
src/middleware/adminMiddleware.js
src/middleware/authMiddleware.js
src/middleware/guestMiddleware.js
src/routes/product.routes.js
src/routes/users.routes.js
src/views/partials/sidebar.ejs
src/views/products/catalogue.ejs
src/views/products/productCart.ejs
src/views/users/all-users.ejs

• Metodo en `usersController` para listar a todos los usuarios
• Vista "cargar usuarios
• Ruta cargarUsuarios

Tr 131 all users view

---

public/css/admin.css
src/controller/productController.js
src/controller/usersController.js
src/routes/users.routes.js
src/views/adminArea.ejs
src/views/partials/adminContent.ejs
src/views/partials/sidebar.ejs
src/views/products/all-products.ejs
src/views/products/newProduct.ejs
src/views/users/all-users.ejs
src/views/users/edit-permissions.ejs

• Vista "editar permisos"
• ruta .get & .put para editar permisos
• método `permissionsProcess` que comprueba y cambian los permisos del usuario
• partial del mensaje de bienvenida del panel de administrador
• Ajustes en `admin.css`

feat: edit permissions view & method

---

public/css/admin.css
public/css/faq.css
public/css/styles.css
src/controller/usersController.js
src/middleware/updateUserMidValidator.js
src/models/data/city.json
src/models/data/users.json
src/views/users/edit-user.ejs

• Json temporal de ciudades para la vista dinámica,
• Inputs nuevos (dirección, piso, ciudad)
• Se modifico el método `userData` para que envié las ciudades
• Se modifico el método `userEdit` para que actualice los nuevos datos (dirección, piso, ciudad).
• Validaciones nuevas para la dirección que ingresa el usuario

feat:user address information required

---

src/controller/usersController.js
src/middleware/registerMidValidator.js
src/views/users/registro.ejs

Se agrega:
- Input para el apellido en el form
- validacion para dicho campo
- atributo 'apellido' en obj User

Tr 157 modificar formulario de registro

---

src/database/models/product.js

Se agrego la tabla productos en su carpeta correspondiente y se realizo las asociaciones.

feat: mapping table products

---

src/database/models/User.js
src/middleware/registerMidValidator.js

Mapeo de tabla User
Creacion de asociaciones con demas tablas

feat: User models and associations

---

src/database/models/productCategory.js

Creacion de modelo productCategory
Asociación con tabla Product

feat: productCategory models and association

---

src/database/models/PurchaseDetail.js
src/database/models/product.js

Se agrego la tabla purchaseDetail con sus relaciones a las tablas City y User.

feat: add table purchaseDetail

---

src/database/models/ItemPurchase.js
src/database/models/PurchaseDetail.js
src/database/models/User.js
src/database/models/UserCategory.js
src/database/models/product.js

feat add itemPurchase model

---

public/css/faq.css
public/css/styles.css
public/css/tyc.css
src/controller/mainController.js
src/controller/productController.js
src/middleware/authMiddleware.js
src/middleware/checkoutDataMidValidator.js
src/models/data/purchaseDetail.json
src/routes/product.routes.js
src/routes/users.routes.js
src/views/faq.ejs
src/views/partials/footer.ejs
src/views/products/checkout.ejs
src/views/products/productCart.ejs
src/views/terminos.ejs
src/views/users/edit-user.ejs

**Se creo la vista `checkout`** 
• Estructura HTML
• Css y responsive
• Rutas `get` y `post`
• Validaciones correspondientes al formulario de envío
• Métodos del controlador para cada ruta

Tr 159 checkout view

---

public/css/styles.css
src/controller/mainController.js
src/controller/productController.js
src/database/models/City.js
src/database/models/PurchaseDetail.js
src/database/models/User.js
src/database/models/product.js
src/database/models/productCategory.js
src/views/index.ejs
src/views/products/all-products.ejs
src/views/products/catalogue.ejs
src/views/products/productDetail.ejs
src/views/products/updateProduct.ejs

****`read productos`****
• métodos  `catalogo`, `selección`, `listar productos` y `detalle de producto` actualizados
• vistas ejs actualizadas con las propiedades de la db

feat:products read methods updated

---

src/controller/productController.js
src/database/models/City.js
src/database/models/PurchaseDetail.js
src/database/models/User.js
src/database/models/UserCategory.js
src/database/models/product.js
src/database/models/productCategory.js
src/views/products/updateProduct.ejs

Método `update` de producto actualizado

feat:crud-update-products

---

public/css/admin.css
src/controller/productController.js
src/views/products/newProduct.ejs
src/views/products/updateProduct.ejs

• Metodo `create `de productos actualizado
• Ciudades agregadas a la vista `updateProduct`
• Refactorización del método `updateProduct`

feat:crud create products

---

src/controller/productController.js
src/controller/usersController.js
src/database/models/User.js
src/routes/users.routes.js
src/views/products/all-products.ejs
src/views/users/all-users.ejs
src/views/users/edit-permissions.ejs
src/views/users/edit-user.ejs

Se creo el método Read del Crud de usuarios.
Se modificaron las vistas de usuarios.
Se modificó metodo Delete del Crud de productos.

feat: add CRUD usuarios: Read

---

src/controller/usersController.js
src/database/models/User.js
src/routes/users.routes.js
src/views/users/all-users.ejs

softDelete para usuarios
metodo "delete" en userController

feat: softDelete for Users DB

---

public/JS/searchAdmin.js
public/css/admin.css
src/controller/productController.js
src/models/data/users.json
src/routes/product.routes.js
src/views/products/all-products.ejs

• Se agrego método que filtra por categoría en ruta `/product/all-products/filter`
• Css a los botones del mismo

Tr 163 crud read product filter admin area

---

public/JS/navSearch.js
public/css/admin.css
public/css/styles.css
src/controller/productController.js
src/routes/product.routes.js
src/views/partials/footer.ejs
src/views/partials/nav.ejs
src/views/products/catalogue.ejs
src/views/products/checkout.ejs

Barra de búsqueda en la navegación
• método que ejecuta una consulta y trae las coincidencias con la variedad y nombre
• script que despliega la misma
• css

feat:search nav method

---

public/JS/editProfileValidation.js
public/css/styles.css
src/controller/usersController.js
src/middleware/updateUserMidValidator.js
src/views/users/edit-user.ejs

Validaciones desde el frontend para la vista `editar usuario`
• nombre
• apellido
• email
• dirección
• departamento
• imagen de perfil
• contraseña

feat:edit profile frontend validations

---

public/JS/editProfileValidation.js
public/JS/loginValidator.js
public/css/login.css
src/middleware/registerMidValidator.js
src/views/users/login.ejs

Se agregan validaciones del lado del front en el login
Se modifica css del login
Se modifica vista del login
Se modifica expresion regular de contraseña

Tr 168 validacion login

---

public/JS/registerValidator.js
src/views/users/registro.ejs

Se creó una carpeta nueva registerValidator.
Se modificó la vista de registro para que aparezcan los errores en cada input.

feat: add front register validator

---

public/JS/editProfileValidation.js
public/JS/loginValidator.js
public/JS/registerValidator.js
public/JS/updateProfileProcess.js
src/controller/usersController.js
src/middleware/loginMidValidator.js
src/middleware/registerMidValidator.js
src/middleware/updateUserMidValidator.js
src/routes/users.routes.js
src/views/partials/head.ejs
src/views/users/edit-user.ejs

• Creación api `edit-user`
• Archivo `updateProfileProcess.js `que consume la misma
• Alerta de actualización exitosa o errores

feat:update profile api & success and error aler

---

src/views/users/login.ejs

Se modifica ejs de la vista login para mostrar los errores

bug: refactor error message

---

public/JS/indexAccessPermission.js
public/css/styles.css
src/views/index.ejs

Se creó un nuevo archivo de js "indexAccessPermission".
Se crearon dos alertas al ingresar al home.

feat: access alert

---

public/JS/indexAccessPermission.js
public/JS/registerValidator.js
src/controller/usersController.js
src/middleware/registerMidValidator.js
src/views/users/registro.ejs

Se refactorizo el código de la validación del registro

refactor: registerValidator

---

public/JS/productCreateValidation.js

se corrigen errores duplicados

bug: resolve duplicate errors

---

public/JS/registerValidator.js

se cambio el array en registerValidator

refactor: array registerValidator

---

public/JS/navAdmin.js
public/JS/productCreateValidation.js
public/css/admin.css
src/views/adminArea.ejs
src/views/partials/navAdmin.ejs
src/views/products/all-products.ejs
src/views/products/newProduct.ejs
src/views/users/all-users.ejs

Se crea archivo js de adminNav
Se modifica css admin
Se agrega script a las vistar

Tr 176 actualizar rutas de los botones admin nav

---

public/JS/registerValidator.js
retro.md

Se agrega retro.md
Se corrigen errores de registerValidator.js

feat: add retro.md

---

package.json
src/middleware/loginMidValidator.js

Se arregla bug al ingresar un usuario inexistente, con la leyenda en el campo de password "Error, primero debe de ingresar un usuario válido"

fix: login password undefined

---

package.json
public/JS/buttonSelection.js
public/css/styles.css
src/views/index.ejs

Se agrego la función click al botón de selección de productos en vista mobile y tablet.

Tr 105 agregar funcion a botones seleccion tr mobile

---

src/controller/api/productsAPIController.js

Se agrego el endpoints para obtener el detalle de producto por id.

feat: endpoints product/:id

---

src/controller/api/productsAPIController.js
tr-dashboard/src/App.css
tr-dashboard/src/Components/Productos/AllProducts/AllProducts.jsx
tr-dashboard/src/Components/Productos/AllProducts/allProducts.css
tr-dashboard/src/Components/Productos/Productos.jsx

Se agrega cuadro con todos los productos
Se modifica app.css
Se modifica api/productAPIController

feat: add card allProducts on Productos component

---

tr-dashboard/src/Components/AllProductsCard/AllProductsCard.jsx
tr-dashboard/src/utils/OneCard/OneCard.js
tr-dashboard/src/utils/OneCard/oneCard.css
tr-dashboard/src/views/Home.css
tr-dashboard/src/views/Home.jsx

se agrega componente AllProductCard

Tr 196 dashboard card con el total de productos en home

---

src/controller/api/usersAPIController.js
tr-dashboard/src/Components/Sidebar/Sidebar.jsx
tr-dashboard/src/Components/Usuarios/UserInfoCard/UserInfoCard.jsx
tr-dashboard/src/utils/OneCard/oneCard.css
tr-dashboard/src/views/Home.css
tr-dashboard/src/views/Home.jsx
tr-dashboard/src/views/Usuarios.css
tr-dashboard/src/views/Usuarios.jsx

cards con datos de usuarios en la view Usuarios

Tr 208 dashboard panel con el listado de usuarios

---

tr-dashboard/src/Components/Sidebar/Sidebar.jsx
tr-dashboard/src/Components/Sidebar/sidebar.css

refactor: css sidebar

---

src/controller/api/productsAPIController.js
tr-dashboard/src/Components/Bienvenida/Bienvenida.css
tr-dashboard/src/Components/Productos/AllProducts/AllProducts.jsx
tr-dashboard/src/Components/Productos/AllProducts/allProducts.css
tr-dashboard/src/utils/OneCard/oneCard.css
tr-dashboard/src/views/Home.css

Se modifica allProducts.jsx cambiando el tamaño del componente principal y agregando detalle del producto
Se modifica allProducts.css
Se refactoriza  productsAPIController

Tr 216 dashboard productos refactor paginado
